### ISSUE TITLE
Documentation Unclear

### ISSUE THREAD

**Issue by ethanpil** [StanDog/npp-phpautocompletion#1]
Its really unclear to me how npp-phpautocompletion determines the class properties and methods. Must the class be declared within the same file that is open in NPP? 

If I include classes in other parts of my project, how will it know the details?

**Comment by StanDog** [comment]
Hello ethanpil,

the plugin uses a root directory to scan and parse PHP files of your project. This root directory needs to be set in the settings (Plugins -> ACCPC (or from v.1.4.1 "PHP autocompletion") -> Settings) in the field *Root directory*. That's all.

The plugin will scan in this directory and it's subdirectories for PHP files and parse them. The first time it may take a few seconds to parse all your files (depends on how much files your project has) but the next time the auto-completion popup will appear instantly. The results of the parsed files are stored in a small internal database so the plugin will parse only modified files again.

Please note that the current document must be a PHP document (in Notepad++ menu: Language -> P -> PHP). Normally, Notepad++ will set this automatically when you open a PHP file. As soon as you type in "->" (object operator) or "::" (static class operator), the plugin will open a small popup which shows you all public attributes and methods of the class in front of the operator. If you want to see the protected and private attributes and methods too, you can activate this in the settings also. ACCPC has also the **PHP Class Inspector**, which is a list of all your classes. It appears as a dock-window on the right side. You can examine all your classes there and even search for attributes and methods:

https://raw.githubusercontent.com/StanDog/npp-phpautocompletion/master/RELEASES/images/accpc_dock.png

You can activate it through a small icon in the toolbar or through the menu: Plugins -> ACCPC (or from v.1.4.1 "PHP autocompletion") -> [x] PHP Class Inspector.

Small example:
1. Create a folder, for example: C:\my_php_files\
2. Download the following file and save it under C:\my_php_files\test.php
   https://raw.githubusercontent.com/StanDog/npp-phpautocompletion/master/Win32/Release/test.php
3. Save the path from step 1 in the settings (Plugins -> ACCPC -> Settings -> Root directory)
4. Open a new tab, set document type to PHP (in Notepad++ menu: Language -> P -> PHP) and type in:

<?php
	$f = new foo();
	$f
?>

If you place the cursor behind "$f" in the 4th line and type in "->" or "::" the auto-completion popup will popup out and show you the attributes and methods from the class "foo" defined in the file test.php.

I hope this clears things up a bit. If not, please ask again. ;-)

**Comment by ethanpil** [comment]
Very useful. Needs to be in the readme.md!

**Comment by ethanpil** [comment]
I have started to get it working. Using F3 ( https://github.com/bcosca/fatfree/ ) this plugin seems to be missing many of the methods... The class names all appear in the inspector, but when I expand them, most methods and attributes are missing.

**Comment by StanDog** [comment]
Nope, you do everything correctly. The plugin is still under development. It works currently for clean code / clean syntax only, which means that all methods and attributes must have a visibility keyword (public / private / protected). Some developers write their OOP code not very well and omit these keywords (although this is valid code too and the Zend engine interprets such properties automatically as public properties). But this makes it harder to parse the PHP code correctly. The methods of classes in F3 have no visibility keyword, so the plugin does not recognize them. I'm planning to add support for this too in one of the next versions.

**Comment by ethanpil** [comment]
Anything I can do to help move this along? :) Would love to see it working...
