### ISSUE TITLE
"an exception occured due to plugin: ccc.dll"

### ISSUE THREAD

**Issue by pbarney** [StanDog/npp-phpautocompletion#10]
Is this plugin still maintained? Does anyone know the cause of this error? It occurs when I type the trigger text `->` or `::`

thanks for any insight.

![image](https://user-images.githubusercontent.com/428178/99885675-d467dd00-2c04-11eb-89e7-86c53808062a.png)

**Comment by StanDog** [comment]
Hi Barney, I was unfortunately inactive on this plugin for a long time. I will try to find some time soon to make the plugin compatible with the latest version of Notepad++. Thanks for your report. :)

**Comment by mredodos** [comment]
pls update with last php version! :)
