### ISSUE TITLE
unfortunately not working with PHP-Namespaces

### ISSUE THREAD

**Issue by nighty985** [StanDog/npp-phpautocompletion#4]
Without PHP Namespaces:
$dbtmp = new GenericDatabaseContainer();
$dbtmp-> #Methods are Displayed

With PHP Namespaces:
$dbtmp = new DB\GenericDatabaseContainer();
$dbtmp-> #Methods are not Displayed

**Comment by StanDog** [comment]
Yes, namespaces are not supported currently but they are planned.

**Comment by JoergKreusel** [comment]
Hello,
long time ago since this post from nighty985. I just installed this nice tool, but the namespace problem seems to be unsolved. Right?
