### ISSUE TITLE
plugin causes non-zero exit value from notepad++

### ISSUE THREAD

**Issue by sdwarwick** [StanDog/npp-phpautocompletion#5]
with this plugin installed,  when notepad++ closes,  it returns with a non-zero exit code.  in one case, it was -1073740286

I need a zero exit code to make notepad++ compatible with other programs.

not sure what you're doing, but it would be nice to have an update that fixes this.

**Comment by StanDog** [comment]
Thank you for your feedback! I'll have a look at it soon.
