### ISSUE TITLE
64bit Version

### ISSUE THREAD

**Issue by tzeumer** [StanDog/npp-phpautocompletion#6]
I just thought about switching to Notepad++ 64 bit? Unfortunately this plugin only has a 32 bit version. Would it be hard to compile a 64 bit version? :)

**Comment by StanDog** [comment]
Thank you for your feedback! I was not actively developing this plugin for some time now. But I will try to update it to the 64-bit version of NPP in the next days. :-)

**Comment by tzeumer** [comment]
@StanDog Great, thanks a lot! 

For the active development part: I'm very happy with the functionality as it is. :)

**Comment by MadTomT** [comment]
@StanDog Did you ever get a chance to do this ? Thanks

**Comment by StanDog** [comment]
Hi @all! I'm sorry I haven't worked on the plugin or replied here in so long. I have a lot to do privately and therefore never got to continue working on the plugin. At the moment I also have some stress with the holidays. To be honest, I had not thought that someone still uses the plugin. I'm glad to see that there is still interest. I will try to find some time soon to update the plugin and fix the bugs. :)

**Comment by matheushvs** [comment]
Your plugin is so good, if you take a time for update this we will be very happy
